[template]
src = "bird_aggr.cfg.template"
dest = "/etc/calico/confd/config/bird_aggr.cfg"
prefix = "/calico/ipam/v2/host/kube-master/ipv4/block"
keys = [
    "/",
]
reload_cmd = "pkill -HUP bird || true"
