[template]
src = "bird6.cfg.no-mesh.template"
dest = "/etc/calico/confd/config/bird6.cfg"
prefix = "/calico/bgp/v1"
keys = [
    "/host/kube-master",
    "/global"
]
check_cmd = "bird6 -p -c {{.src}}"
reload_cmd = "pkill -HUP bird6 || true"
