[template]
src = "bird.toml.template"
dest = "/conf.d/bird.toml"
prefix = "/calico/bgp/v1/global"
keys = [
    "/node_mesh",
]
reload_cmd = "echo -e 'POST /containers/calico-confd/restart?t=0 HTTP/1.0\r\n' | nc -U /docker.sock"
